# Generated by Django 4.0.7 on 2022-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_activation_link_activationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_link',
            field=models.CharField(default='create_activation_link', max_length=255),
        ),
        migrations.DeleteModel(
            name='ActivationLink',
        ),
    ]
