# Generated by Django 4.0.7 on 2022-08-08 18:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_activation_link_delete_activationlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_link',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_link1',
            field=models.CharField(blank=True, default=user.models.crete_activation_link, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_link2',
            field=models.CharField(blank=True, default=user.models.crete_activation_link, max_length=50, null=True),
        ),
    ]
